# Generated by Django 3.0.6 on 2020-05-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='Post',
            new_name='post',
        ),
    ]
